from mas2graph.models.dual_srgnn import LightningDualSRGNNRegressor, DualSRGNNRegressor
from mas2graph.models.mlp import LightningMLPRegressor
from mas2graph.models.gat_regressor import LightningGATRegressor
from mas2graph.models.dual_gnn import LightningDualGNNRegressor
